-- MySQL Script generated by MySQL Workbench
-- Tue Mar 19 19:51:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ALUNO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ALUNO` ;

CREATE TABLE IF NOT EXISTS `ALUNO` (
  `CPF` VARCHAR(22) NOT NULL,
  `Nome` VARCHAR(60) NOT NULL,
  `Sobrenome` VARCHAR(60) NULL,
  `Sexo` CHAR(1) NULL,
  `DataNasc` DATE NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AREA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AREA` ;

CREATE TABLE IF NOT EXISTS `AREA` (
  `Nome` VARCHAR(45) NOT NULL,
  `Sigla` VARCHAR(10) NOT NULL,
  `SuperArea` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_AREA_AREA1`
    FOREIGN KEY (`SuperArea`)
    REFERENCES `AREA` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_AREA_AREA1_idx` ON `AREA` (`SuperArea` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `CURSO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CURSO` ;

CREATE TABLE IF NOT EXISTS `CURSO` (
  `Sigla` VARCHAR(10) NOT NULL,
  `Nome` VARCHAR(60) NULL,
  `Horas` INT NULL,
  `Custo` FLOAT NULL,
  `Area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_CURSO_AREA`
    FOREIGN KEY (`Area`)
    REFERENCES `AREA` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CURSO_AREA_idx` ON `CURSO` (`Area` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `MATRICULA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MATRICULA` ;

CREATE TABLE IF NOT EXISTS `MATRICULA` (
  `Data` DATE NOT NULL,
  `Pago` TINYINT NOT NULL,
  `Aluno` VARCHAR(22) NOT NULL,
  `Curso` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Aluno`, `Curso`),
  CONSTRAINT `fk_MATRICULA_ALUNO1`
    FOREIGN KEY (`Aluno`)
    REFERENCES `ALUNO` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATRICULA_CURSO1`
    FOREIGN KEY (`Curso`)
    REFERENCES `CURSO` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_MATRICULA_CURSO1_idx` ON `MATRICULA` (`Curso` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `MODULO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MODULO` ;

CREATE TABLE IF NOT EXISTS `MODULO` (
  `Nome` VARCHAR(30) NOT NULL,
  `Curso` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Curso`),
  CONSTRAINT `fk_MODULO_CURSO2`
    FOREIGN KEY (`Curso`)
    REFERENCES `CURSO` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROFESSOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROFESSOR` ;

CREATE TABLE IF NOT EXISTS `PROFESSOR` (
  `CPF` VARCHAR(22) NOT NULL,
  `Nome` VARCHAR(30) NULL,
  `CURSO_Sigla` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`CPF`, `CURSO_Sigla`),
  CONSTRAINT `fk_PROFESSOR_CURSO1`
    FOREIGN KEY (`CURSO_Sigla`)
    REFERENCES `CURSO` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PROFESSOR_CURSO1_idx` ON `PROFESSOR` (`CURSO_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `TOPICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TOPICO` ;

CREATE TABLE IF NOT EXISTS `TOPICO` (
  `Sigla` VARCHAR(10) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Horas` INT NULL,
  `Modulo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Sigla`, `Modulo`),
  CONSTRAINT `fk_TOPICO_MODULO1`
    FOREIGN KEY (`Modulo`)
    REFERENCES `MODULO` (`Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TOPICO_MODULO1_idx` ON `TOPICO` (`Modulo` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
